org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.3

# Mod
mod_version=1.7.4+mc26.3
maven_group=com.threecolumnsstudio.villagerphrases
mod_id=villagerphrases

# Fabric
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.5+26.3

# NeoForge
# Check latest at https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.3.0.1-beta